name:                lcd-assignment
version:             0.1.0.0
github:              "MicheGit/lcd-assignment"
license:             BSD-3-Clause
author:              "Christian Micheletti"
maintainer:          "christian.micheletti@studenti.unipd.it"
copyright:           "2024 Christian Micheletti"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/MicheGit/lcd-assignment#readme>

dependencies:
- base >= 4.7 && < 5
- megaparsec
- text
- containers
- parallel
- time
- lattices

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

default-extensions:
- GADTs
- OverloadedStrings
- LambdaCase
- ImplicitParams
- RankNTypes
- InstanceSigs
- FlexibleInstances
- TupleSections
- DefaultSignatures
- DeriveAnyClass
- TypeFamilies
- FlexibleContexts

library:
  source-dirs: src

executables:
  lcd-assignment-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N4
    dependencies:
    - lcd-assignment

tests:
  lcd-assignment-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lcd-assignment
    - hspec
    - megaparsec
